version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env  # Memuat variabel environment dari .env file
    # environment:
      # NODE_ENV: production  # Bisa tambahkan variabel tambahan jika diperlukan
